baseURL = 'https://konkin-ivan.github.io'
languageCode = 'ru-ru'
title = 'Мой крутой блог на Hugo'
theme = 'programmister'   # ananke, harbor, hermit

[taxonomies]
  tag = "tags"
  category = "categories"

# Дополнительные настройки для темы
[params]
  description = "Описание моего блога"

[services.rss]
  limit = 20

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    guessSyntax = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
