baseURL = 'https://konkin-ivan.github.io'
languageCode = 'ru-ru'
title = 'Мой крутой блог на Hugo'
theme = 'hugo-coder'   # ananke, harbor, hermit

# Дополнительные настройки для темы
[params]
  description = "Описание моего блога"

# Добавьте эту строку:
publishDir = 'root'
