name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        run: |
          # Скачиваем и устанавливаем Hugo напрямую
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.125.4/hugo_extended_0.125.4_linux-amd64.deb
          sudo dpkg -i hugo.deb
          hugo version

      - name: Build site
        run: hugo --minify

      - name: Create gh-pages branch
        run: |
          # Создаем ветку gh-pages вручную
          cd public
          git init
          git checkout -b gh-pages
          git add .
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "Deploy Hugo site"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages --force

      - name: Wait for deployment
        run: sleep 30  # Даем время GitHub Pages развернуть сайт
